// Copyright 2023-2024 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.

/*********************************/
/* AUTOGENERATED. DO NOT MODIFY! */
/*********************************/

// control_ret_t enum value to enum string mapping
const char *control_ret_str_map[] = 
{
{% for i in str_map %}
    "{{i}}",
{% endfor %}
};